feat: allow to change username
graasp/graasp-account pull request #180
Opened 2024-03-28 11:34 UTC by mariembencheikh

2024-03-28 14:57 UTC, pyphilia requested changes
I added some intermediary comments, I'm looking forward the changes for the layout and the validation!

2024-03-28 14:57 UTC, pyphilia commented on src/langs/de.json
> +  "PROFILE_EDIT_USERNAME_BUTTON": "Speichern",
Thanks for adding all the translations. But actually we have a tool to handle that, so feel free to fill for languages you know, and let empty for languages you don't know^^

2024-03-28 14:57 UTC, pyphilia commented on src/langs/es.json
> +  "PROFILE_MEMBER_NAME": "nombre de usuario",
```suggestion
  "PROFILE_MEMBER_NAME": "Nombre de usuario",
```

2024-03-28 14:57 UTC, pyphilia commented on src/langs/it.json
> +  "PROFILE_MEMBER_NAME": "nome utente",
```suggestion
  "PROFILE_MEMBER_NAME": "Nome utente",
```

2024-03-28 14:57 UTC, pyphilia commented on src/langs/it.json
> +  "PROFILE_EDIT_USERNAME_BUTTON": "registrare",
```suggestion
  "PROFILE_EDIT_USERNAME_BUTTON": "Registrare",
```

2024-03-28 14:57 UTC, pyphilia commented on src/pages/MemberScreen.tsx
> +                  )}
Since this feature is quite well encapsulated, I think you can create a new file with this component only.

2024-03-28 14:57 UTC, pyphilia commented on src/pages/MemberScreen.tsx
> +                <Typography>
You can remove the `Typography` tag.

2024-03-28 15:23 UTC, spaenleh requested changes
I agree with the comments of @pyphilia especially the ones for the translations 😉 Looking forward to your next changes. 

Do not forget to:
- include a screenshot in the PR description. Even a very short video with the interaction would be a nice touch.
- add a reference to the issue you are fixing in the PR description so it can be auto-closed. Otherwise we have to do some manual cleanup 😕

2024-03-28 15:23 UTC, spaenleh commented on src/langs/ar.json
> +}
You are missing a newline here. Configure your text editor as follows: 
```json
"files.insertFinalNewline": true
```

2024-03-28 15:23 UTC, spaenleh commented on src/pages/MemberScreen.tsx
> +                    sx={{ mr: 2 }}
If this is used for spacing, we prefer to use a stack with the `spacing` property. Is is more flexible and lets you re-arrange element with ease, without needing to move the margin property to the first element.
```tsx
<Stack direction="row" spacing={2}>
  <Textfield
  ....
  />
  {
    ....
  }
</Stack>
```

2024-04-02 07:27 UTC, spaenleh requested changes
Nice changes, I have added some comments, please review them and let me know if you have questions. We are on the right path ! 👍

2024-04-02 07:27 UTC, spaenleh commented on src/components/main/EditUsername.tsx
> +  const [newUsername, setNewUsername] = useState(memberName || '');
This useState creates a state that does not react to external changes of the username. In the current situation it is not really an issue because the full component tree is re-created when the current member query is re-fetched. 
But be careful with such implementations. Once side-issue however is that if you are editing the name, and the current member query is refetched, you will loose your changes. 

There currently is no websocket feedback on member update, so if you have two windows open and change your name in one it will not propagate to the other windows unless you manually refresh them. Would be nice to have some feedback there maybe.

2024-04-02 07:27 UTC, spaenleh commented on src/components/main/EditUsername.tsx
> +      {isEditing ? (
You have this conditional multiple times in your JSX. Would it make sens to create a new component for the Editing name ? and then you can add a `if` and render the right component based on `isEditing` I think explicit ifs are clearer than using ternary expressions in JSX for some cases.

2024-04-02 13:55 UTC, mariembencheikh commented on src/components/main/EditUsername.tsx
> +  const [newUsername, setNewUsername] = useState(memberName || '');
More details please, how it must be

2024-04-02 16:20 UTC, spaenleh requested changes

2024-04-02 16:20 UTC, spaenleh commented on src/components/main/EditingNameField.tsx
> +  };
Put this function outside of your component.

2024-04-02 16:20 UTC, spaenleh commented on src/pages/MemberScreen.tsx
> +                <EditUsername member={member} />
Would it make sens to rename this component to `UsernameForm` ?

2024-04-02 16:20 UTC, spaenleh commented on src/components/main/EditUsername.tsx
>    );
Refactor this to be:
```tsx
if (isEditing) {
  return <EditingComponent/>
}
return <DisplayComponent/>
```

I think it is clearer than using the ternary operator.

2024-04-02 16:20 UTC, spaenleh commented on src/components/main/EditUsername.tsx
> +    <Stack direction="row" spacing={2} alignItems="center">
This `Stack` is not necessary I think.

2024-04-02 16:20 UTC, spaenleh commented on src/components/main/EditingNameField.tsx
> +      </Button>
If you do not want to have the space between the two buttons here, you can group them.

2024-04-02 16:25 UTC, spaenleh commented
@mariembencheikh Can you test that you can update a name even if there are some spaces at the end ?

2024-04-02 16:35 UTC, spaenleh commented on src/components/main/EditUsername.tsx
> +  const [newUsername, setNewUsername] = useState(memberName || '');
@mariembencheikh 
Whenever you create a state that gets an initial value from the props you will face a potential de-synchronisation. This is because the state will not be updated if the prop changes. To synchronise the state with prop changes you usually have to add a `useEffect`. 

In our case, the props is actually coming from an API call, so this is data from the server. 
Imagine that the user opens 2 windows. He changes the username in the first window. In the second window, imagine there is a mechanism to notify of the data change on the server (this can be a websockets update). It would result in a new call to your component with the name prop having a new value. But the state would not get updates unless you add a `useEffect` that react to updates of the name prop and sets the state accordingly. 

This is for the theory.
In practice with our example, when the data from the server changes, or is refetched manually by using the react-query dev tools (little flower at the bottom of the screen), nearly all the component tree is re-created, and thus the state is re-created with the new initial value. I just wanted to raise your attention to the de-synchronisation issue, as this is a common mistake. 

The last part of my comment was suggesting potential improvements.
If we take the example with multiple windows (even multiple tabs), I think it would be nice for the updated username to be propagated all the windows and tabs. Can you think of a way to do this ? Would you like to work on this task ? I think it would add a great value for the user, seeing up-to-date data on all open windows without having to refresh the pages manually.

2024-04-03 08:09 UTC, mariembencheikh commented on src/components/main/EditingNameField.tsx
> +      </Button>
I want to have the space between

2024-04-03 14:08 UTC, spaenleh requested changes
Thank you for the changes. 

Please be consistent in your naming conventions. 
Import your components with the same name as the file. 
Use consistent PascalCase for files, components and types. 

Apply the requested changes and request a review.
I have deployed the changes to dev, for the team to test.
Discuss with @MartinaVin to see if she has some improvements to propose design-wise. I am not really a fan of the `Button` for validate and cancel. I think we should use `IconButton`.

Sometimes you use `UserName` sometimes `Username`.

2024-04-03 14:08 UTC, spaenleh commented on src/langs/de.json
> +  "PROFILE_EDIT_USERNAME_BUTTON": "Speichern",
Also it says "save" and the constant says "edit" maybe it needs to be adapted.

2024-04-03 14:08 UTC, spaenleh commented on src/langs/ar.json
> +}
Add a newline to this file please.

2024-04-03 14:08 UTC, spaenleh commented on src/langs/en.json
> +  "USERNAME_LENGTH_ERROR": "Username must be between 3 and 30 characters long"
Use interpolation to pass the min and max values.

2024-04-03 14:08 UTC, spaenleh commented on src/pages/MemberScreen.tsx
> +import UsernameForm from '@/components/main/Usernameform';
Be consistent in the import name and file name casing. We prefer `UsernameForm`

2024-04-04 07:54 UTC, mariembencheikh commented on src/components/main/EditingNameField.tsx
> +let errorMessage;
ok it's noted

2024-04-04 10:04 UTC, spaenleh requested changes
Nice, nearly there. Also having the tests will be nice !

2024-04-04 10:04 UTC, spaenleh commented on src/components/main/EditingNameField.tsx
> +            MAX: MAX_USERNAME_LENGTH,
Our convention for interpolation keys is to use camelCase.
```suggestion
            min: MIN_USERNAME_LENGTH,
            max: MAX_USERNAME_LENGTH,
```

2024-04-10 12:47 UTC, spaenleh requested changes

2024-04-10 12:47 UTC, spaenleh commented on cypress/e2e/profile.cy.ts
> +  cy.visit('/');
Put this in a `beforeEach` hook.

2024-04-10 12:47 UTC, spaenleh commented on src/config/selectors.ts
> +export const ID_MEMBER_NAME_TEXT = 'member-name';
Our naming convention is to put the `_ID` as a suffix. And to start by the feature this targets:
`USERNAME_SAVE_BUTTON_ID` for example

2024-04-10 12:47 UTC, spaenleh commented on package.json
> +    "@types/jest": "29.5.12",
Est-ce que tu peux préciser pourquoi tu as ajouté ce packet ? il ne me semble pas que on utilise jest dans ce projet.

2024-04-10 12:47 UTC, spaenleh commented on cypress/e2e/profile.cy.ts
>  describe('template spec', () => {
Change name of test suite.

2024-04-10 12:47 UTC, spaenleh commented on cypress/e2e/profile.cy.ts
>    it('passes', () => {
Update test name

2024-04-10 12:47 UTC, spaenleh commented on cypress/e2e/profile.cy.ts
> +  it('button back not modify the username', () => {
```suggestion
  it('should not update the user name if canceling edit', () => {
```

2024-04-10 12:47 UTC, spaenleh commented on cypress/e2e/profile.cy.ts
> +  it('button back not modify the username', () => {
Use consistent spacing.

2024-04-10 12:47 UTC, spaenleh commented on cypress/cypress.d.ts
> +    setUpApi(args?: any): Chainable;
is this change needed ?

2024-04-10 14:23 UTC, mariembencheikh commented on cypress/cypress.d.ts
> +    setUpApi(args?: any): Chainable;
Yes you have right, when i'm working with tests i  was obliged to add "?" and then i forget to remove it

2024-04-11 08:48 UTC, mariembencheikh commented on package.json
> +    "@types/jest": "29.5.12",
Je ne me souviens pas de ce packet,

2024-04-12 11:28 UTC, spaenleh requested changes
Thank you for the changes.
Please fix all comments.

2024-04-12 11:28 UTC, spaenleh commented on cypress/e2e/profile.cy.ts
>    it('passes', () => {
Please rename this test. `passes` is not a good name.

2024-04-12 11:28 UTC, spaenleh commented on src/config/selectors.ts
> +export const MEMBER_NAME_TEXT_ID = 'member-name';
I made a suggestion for these, actually I want you to apply the naming suggested. `BUTTON_SHOW_EDIT_FORM_ID` is too broad. Use more specific names. Also they should be consistent with one another. 

Here you have `CURRENT_USERNAME_ID` and `MEMBER_NAME_TEXT_ID`, they both identify the username UI element, one when it is editable, and  the other when it is simply displaying. They should have something In common in the name don't you think ?

Also you actual ids are too generic. `button` is not a good id to use. 

Below are values I think follow these guidelines. Do you agree that they:
- are easier to find and reference
- express better the intent
- are consistent
```suggestion
export const USERNAME_EDIT_BUTTON_ID = 'username-edit-button';
export const USERNAME_SAVE_BUTTON_ID = 'username-save-button';
export const USERNAME_CANCEL_BUTTON_ID = 'username-cancel-button';
export const USERNAME_INPUT_FIELD_ID = 'username-input-field';
export const USERNAME_DISPLAY_ID = 'username-display';
```
Please use these names.

2024-04-12 11:28 UTC, spaenleh commented on src/components/main/UsernameForm.tsx
> +    </>
I deployed the latest code from the branch to dev and this is the display:
<img width="1017" alt="Screenshot 2024-04-12 at 13 23 30" src="https://github.com/graasp/graasp-account/assets/39373170/6767ffeb-1917-4115-8064-b15a42cdbe63">
Is it intentional to have the pen icon below the name ?

2024-04-12 11:28 UTC, spaenleh commented on src/components/main/EditingNameField.tsx
> +      <TextField
Add the `autofocus` prop to this textfield, so the input is focused when you open it. This will be nicer

2024-04-15 05:49 UTC, spaenleh requested changes

2024-04-15 05:49 UTC, spaenleh commented on cypress/e2e/profile.cy.ts
> +  it.only('Saves username after trimming trailing space', () => {
Remove `.only`

2024-04-15 05:49 UTC, spaenleh commented on cypress/e2e/profile.cy.ts
> +    cy.intercept('PUT', '/api/edit-member').as('editMember');
This intercept is wrong. Look at the [api call definition in graasp-query-client](https://github.com/graasp/graasp-query-client/blob/7adee31677b9f0785b3bc4fd5cad9d843dae1ec8/src/api/member.ts#L93)
You test works, because there is already an intercept defined that matches the right call and that is called `editMember` in [the cypress/support/server.ts file](https://github.com/graasp/graasp-account/blob/918ea40f9b1b4fc1f76510c06280c5ab8acf71c8/cypress/support/server.ts#L93)

2024-04-15 05:49 UTC, spaenleh commented on src/components/main/UsernameForm.tsx
> +    </Grid>
In this case `Grid` is not the right choice I think. Prefer [`Stack`](https://mui.com/material-ui/react-stack/) as it allows for 1-dimensional arrangement of data, where grid is 2-dimensional. Also grid has some weird margin/padding behavior. 

```suggestion
    <Stack direction="row" alignItems="center" spacing={1}>
      <Box id={USERNAME_DISPLAY_ID}>{member.name}</Box>
      <IconButton
        onClick={() => setIsEditing(true)}
        id={USERNAME_EDIT_BUTTON_ID}
      >
        <ModeEdit />
      </IconButton>
    </Stack>
```
Also with stack you do not need to wrap the elements again in a `<Grid item ...`

2024-04-16 09:53 UTC, merged