1/update app
graasp/graasp-account pull request #2
Opened 2022-06-16 14:28 UTC by Julien-Torrent

close #1

2022-07-12 15:25 UTC, pyphilia requested changes
Thanks for the PR, I've adde my comments.
I've also changed query client recently, maybe check the new config structure.

2022-07-12 15:25 UTC, pyphilia commented on src/components/common/AddCardModal.js
> +          queryClient.invalidateQueries("cards");
Create key `cards` and reuse. Maybe go for `[subscription, cards]`? Or similar, so it's clearer.

2022-07-12 15:25 UTC, pyphilia commented on src/components/common/CardList.js
> +            {card?.brand?.toUpperCase()} <br /> •••• •••• ••••{" "}
remove `{" "}`

2022-07-12 15:25 UTC, pyphilia commented on src/components/main/PaymentConfirmation.js
> +    return <></>;
return null?

2022-07-12 15:25 UTC, pyphilia commented on src/components/main/PaymentConfirmation.js
> +    return <></>;
return null?

2022-07-12 15:25 UTC, pyphilia commented on src/components/main/PaymentConfirmation.js
> +                  /mo
Translate?

2022-07-12 15:25 UTC, pyphilia commented on src/components/context/CheckoutModalContext.js
> +  cardId: PropTypes.string.isRequired,
Card id can be undefined.

2022-07-12 15:25 UTC, pyphilia commented on src/components/main/PaymentConfirmation.js
> +        cardId={selectedCardId !== customer?.get("defaultCard") ? selectedCardId : undefined}
Is this check necessary? Why not just return selectedCardId?

2022-07-12 15:25 UTC, pyphilia commented on src/components/main/PaymentOptions.js
> +        <Typography variant="h5">{t("My Cards:")}</Typography>
I remember a problem with `:` or `.` at the end of strings. Is this displayed?

2022-07-12 15:25 UTC, pyphilia commented on src/components/main/Subscriptions.js
> +  const [currency, setCurrency] = useState("chf");
Factor out default currency.

2022-07-12 15:25 UTC, pyphilia commented on src/components/main/Subscriptions.js
> +  };
Use braces.

2022-07-12 15:25 UTC, pyphilia commented on src/components/main/Subscriptions.js
> +            <Select id="id" native value={currency} onChange={handleChange}>
Is the id used?

2022-07-12 15:25 UTC, pyphilia commented on src/components/main/Subscriptions.js
> +                      )}
Might be interesting to factor out as a function.

2022-07-12 15:25 UTC, pyphilia commented on src/components/main/Subscriptions.js
>                        /mo
Translate.

2022-07-13 07:42 UTC, Julien-Torrent commented on src/components/main/PaymentConfirmation.js
> +        cardId={selectedCardId !== customer?.get("defaultCard") ? selectedCardId : undefined}
Yes, because if the customer wants to use the default card and then changes it, we should still debit on the default card.

2022-07-15 12:29 UTC, pyphilia approved these changes

2022-07-15 14:26 UTC, merged