feat: create home page
graasp/graasp-account pull request #228
Opened 2024-05-10 14:01 UTC by mariembencheikh

<img width="2553" alt="image" src="https://github.com/graasp/graasp-account/assets/58473159/46a72454-504a-4afc-8ba9-d4b92d5bd3b8">
#218

2024-05-13 11:53 UTC, pyphilia submitted a review, later dismissed
Thanks for this PR, I've left some comments, let me know if you have questions! 🚋 
Also you mentioned already existing tests not passing, but I expect more tests for the home page as well. It might be difficult to test changing avatar, but perhaps:
- not logged in user gets redirected
- having a thumbnail does not show the tip
- having no thumbnail shows the tip
- showing correct member info

2024-05-13 11:53 UTC, pyphilia commented on cypress/e2e/profile.cy.ts
> +    cy.visit('/profile');
Use `PROFILE_PATH`

2024-05-13 11:53 UTC, pyphilia commented on cypress/e2e/profile.cy.ts
> +      cy.visit('/profile');
Same as above.

2024-05-13 11:53 UTC, pyphilia commented on cypress/e2e/profile.cy.ts
> +      cy.visit('/profile');
Same as above.

2024-05-13 11:53 UTC, pyphilia commented on cypress/e2e/profile.cy.ts
> +    cy.visit('/profile');
Same as above.

2024-05-13 11:53 UTC, pyphilia commented on cypress/e2e/profile.cy.ts
> +    cy.visit('/profile');
Same as above.

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/GraaspIcons.tsx
> +    >
It does not work well on small screens 
![Screenshot 2024-05-13 at 13 32 53](https://github.com/graasp/graasp-account/assets/11229627/73a1830f-7698-4d26-b303-1ad6e7bc2a79)
Maybe let's have 2 rows with 2 elements?

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/MemberCard.tsx
> +  // const memberId = member?.id;
Remove?

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/MemberCard.tsx
> +        itemId: memberId,
I know it's not your original code, but do you think could change it? It would be best `configureAvatarUppy` receive `memberId` instead of `itemId`.

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/MemberCard.tsx
> +              <Typography variant="h4">Welcome,</Typography>
Translate

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/MemberCard.tsx
> +                {t('PROFILE_CREATED_AT_TITLE')}{' '}
```suggestion
                {t('PROFILE_CREATED_AT_TITLE')}
```

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/MemberCard.tsx
> +        <Box>
Do you need this box? Just wondering.

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/MemberCard.tsx
> +              <Grid item sm={6}>
Do you need this Grid?

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/MemberCard.tsx
> +              <Box marginTop={1} alignItems="center" justifyContent="center">
Maybe it's more interesting to use Stack? Do you need it actually? use `gap` in the Stack above to remove `marginTop`?

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/NotifCard.tsx
> +// import { ImageUp, ShieldAlert } from 'lucide-react';
Remove?

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/NotifCard.tsx
> +      </Grid> */}
Remove

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/NotifCard.tsx
> +    );
Not good to have duplicated code compared to MemberCard. Factor out the similar bit of code from both files (as util functions or custom hook).

2024-05-13 11:53 UTC, pyphilia commented on src/components/main/NotifCard.tsx
> +        </Card>
This shouldn't show if the user already has a thumbnail.

2024-05-13 11:53 UTC, pyphilia commented on src/langs/en.json
> +  "PERSONALISATION_INFORMATION": "Let your personality and uniqueness shine by adding a profile picture !"
```suggestion
  "PERSONALISATION_INFORMATION": "Let your personality and uniqueness shine by adding a profile picture!"
```

2024-05-13 11:53 UTC, pyphilia commented on src/langs/fr.json
> +  "PERSONALISATION_TITLE": "Personalisation",
```suggestion
  "PERSONALISATION_TITLE": "Personnalisation",
```

2024-05-13 11:53 UTC, pyphilia commented on src/pages/HomePage.tsx
> +    <Stack spacing={8} paddingTop={5}>
```suggestion
    <Stack spacing={8} marginTop={5}>
```

2024-05-15 14:21 UTC, spaenleh requested changes
Thank you for the changes. I think you need to address the code duplication issue. 

I don't think you need to have the ability to click the tip card about the profile picture to upload a new picture. Honestly it does not makes sens to me. I would prefer to be able to select a new picture by clicking the avatar. If you add a mouse overlay that suggests you can do so, it will be even better. I am also not convinced by the `upload picture` button below the avatar. Ask @ReidyT how he did the overlay to upload a new picture in the library publication PR. 

I think tests for the home page are still missing.

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/MemberAvatar.tsx
> +  maxHeight = 40,
Why remove the constant ?

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/MemberCard.tsx
> +  } = avatarUpload;
De-structure directly.

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/MemberCard.tsx
> +            <Grid item sm={6}>
I don't see a Grid parent here. You should probably remove this Grid wrapper.

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/MemberCard.tsx
> +            <Box marginTop={1} alignItems="center" justifyContent="center">
use `gap` or `spacing` prop on the stack instead of adding top/left margins.

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/MemberCard.tsx
> +      <Box>
This box is useless.

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/MemberCard.tsx
> +      {StatusBarComponent}
Why do you have the `StatusBarComponent` twice ?

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/MemberCard.tsx
> +      )}
I don't think this should be that high in the tree. Put it closer to the avatar picture, make a separate component if you need.

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/MemberCard.tsx
> +            <Typography variant="h4">Welcome,</Typography>
Translate.

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/MemberCard.tsx
> +      {StatusBarComponent}
This duplicated usage makes the user profile picture crash. Did you test it ?

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/NotifCard.tsx
This file has a lot of duplication with the MemberCard file. Find a way to re-use a component.

2024-05-15 14:21 UTC, spaenleh commented on src/components/main/useAvatarUpload.tsx
> +            onUploadAvatar({ id: member.id, data });
Here you should close the status bar by calling `handleClose` or `setOpenStatusBar(false)`

2024-05-15 14:28 UTC, spaenleh commented on src/components/main/NotifCard.tsx
> +      <Grid xs={12} md={6} item>
Grid has issues with un-even margins. If you really need use `Grid2` from `unstable`.
![Uploading Screenshot 2024-05-15 at 16.23.29.png…]()

2024-05-15 14:28 UTC, spaenleh commented on src/components/main/MemberCard.tsx
> +              {formatDate(member?.createdAt, { locale: i18n.language })}
The spacing between these 2 elements does not work since they are rendered as text nodes:
<img width="394" alt="Screenshot 2024-05-15 at 16 23 49" src="https://github.com/graasp/graasp-account/assets/39373170/04e70c62-5a7d-4574-a543-b653705a0c01">

2024-05-15 14:29 UTC, mariembencheikh commented on src/components/main/MemberCard.tsx
> +      {StatusBarComponent}
ahh i forget to remove it

2024-05-16 09:51 UTC, mariembencheikh commented
> Thank you for the changes. I think you need to address the code duplication issue.
> 
> I don't think you need to have the ability to click the tip card about the profile picture to upload a new picture. Honestly it does not makes sens to me. I would prefer to be able to select a new picture by clicking the avatar. If you add a mouse overlay that suggests you can do so, it will be even better. I am also not convinced by the `upload picture` button below the avatar. Ask @ReidyT how he did the overlay to upload a new picture in the library publication PR.
> 
> I think tests for the home page are still missing.



> Thank you for the changes. I think you need to address the code duplication issue.
> 
> I don't think you need to have the ability to click the tip card about the profile picture to upload a new picture. Honestly it does not makes sens to me. I would prefer to be able to select a new picture by clicking the avatar. If you add a mouse overlay that suggests you can do so, it will be even better. I am also not convinced by the `upload picture` button below the avatar. Ask @ReidyT how he did the overlay to upload a new picture in the library publication PR.
> 
> I think tests for the home page are still missing.

2024-05-27 06:11 UTC, spaenleh commented on src/components/main/MemberAvatar.tsx
> +  maxHeight = 40,
@mariembencheikh I don't think was resolved. You should have this size defined as a constant. The constant can live in this file.

2024-05-27 12:33 UTC, spaenleh reviewed
One last comment.

2024-05-27 12:33 UTC, spaenleh commented on src/config/constants.ts
> +export const AVATAR_HEADER_SIZE = 40;
Since this constant is used only in the `MemberAvatar` file there is no need to have it here, move it to the `MemberAvatar` file. 

Keeping constants local and close to where they are used is a good practice to reduce pollution of the global scope/files. Once the code changes, maybe you need to move these constants to a common file, since they might be used in multiple places.

2024-05-27 13:26 UTC, spaenleh approved these changes

2024-05-28 09:32 UTC, merged