241 create read only profile page
graasp/graasp-account pull request #244
Opened 2024-05-30 12:59 UTC by mariembencheikh

#241

2024-05-31 11:35 UTC, pyphilia requested changes
Great PR! I added my comments, as well as general/design comments here:

I think it was not especially wanted to have this break effect (title-button). I think it's okay to not break, but rather use `xs=10` `xs=2` or 11/1
<img width="567" alt="Screenshot 2024-05-31 at 13 19 19" src="https://github.com/graasp/graasp-account/assets/11229627/df71fabb-b1f2-4633-82fc-9920738f1828">

I think the display is bit strange when the public profile is empty. Maybe let's have some indication that some fields are empty?
<img width="1116" alt="Screenshot 2024-05-31 at 13 23 45" src="https://github.com/graasp/graasp-account/assets/11229627/894450c9-c7a9-4a43-81b4-508dccd71fcf">

Typo dans "membre depuis"
<img width="771" alt="Screenshot 2024-05-31 at 13 28 03" src="https://github.com/graasp/graasp-account/assets/11229627/690719dd-b728-4e65-993b-317d760726dd">

Also I know it was not in the mockup, but I think it would be interesting to have the link to the public profile in the read page as well.

2024-05-31 11:35 UTC, pyphilia commented on src/pages/MemberScreen.tsx
>  const MemberProfileScreen = (): JSX.Element | null => {
Rename file like the name of the component `MemberProfileScreen`

2024-05-31 11:35 UTC, pyphilia commented on cypress/e2e/memberProfile.cy.ts
> +  it('displays the correct public profile info', () => {
Let's also add a test when the public profile is empty. It's interesting to check, because sometimes when info is unavailable a page can crash.

2024-05-31 11:35 UTC, pyphilia commented on src/components/main/MemberPersonalInformation.tsx
> +          >
Use `react-router-dom`'s `Link` to avoid using `navigate` directly. https://reactrouter.com/de/main/components/link

2024-06-03 07:29 UTC, spaenleh requested changes
Good work. I have a few comments:

- [x] change PR title to conform to the standard (for reference see [the style guide](https://graasp.github.io/docs/developer/style-guide/#conventional-pr-title))
- [ ] your PR has not been rebased, it is not dramatic, but would be better to do in the future, as it provides a clearer view of the changes you want to apply
- [x] the Changelog has been formatted, you should not format files you do not care about. To avoid committing files you do not wish to change, review your changes locally, or in github and revert any change you do not wish to make. (Refer to [the style guide](https://graasp.github.io/docs/developer/style-guide/#review-your-changes-before-asking-for-reviews) for more info)
- [x] Once you edit one part of the profile, there is no way to return back to the profile page. Add a button even if only temporary, so that users are not lost.
- [x] In general you have repeating code, create components to re-use and make it easier to change layout more uniformly.

2024-06-03 07:29 UTC, spaenleh commented on src/components/main/MemberPersonalInformation.tsx
> +      </Grid>
I do not see the advantage of using a `Grid` here. A simple stack is less verbose and more flexible (pun intended).
```suggestion
      <Stack direction="row" justifyContent="space-between" spacing={2}>
        <Typography variant="h5">{t('PERSONAL_INFORMATION_TITLE')}</Typography>
        <Link to={EDIT_MEMBER_INFO} className="link">
          <Button variant="contained" color="primary">
            {t('EDIT_BUTTON')}
          </Button>
        </Link>
      </Stack>
```

With grid since you divide the space into 2 equal zones (`sx={6}`) you can have un-natural wrapping:
<img width="396" alt="Screenshot 2024-06-03 at 08 58 23" src="https://github.com/graasp/graasp-account/assets/39373170/c1442960-5714-485f-8a80-9006f100f8c5">
I would expect the text to have the space to not have to wrap on a second line here. 

When using the provided Stack solution it does not happen, since the text container is not constrained to taking only half the width:
<img width="402" alt="Screenshot 2024-06-03 at 09 00 57" src="https://github.com/graasp/graasp-account/assets/39373170/fe41c774-e110-4f2f-931c-211ac629ffb3">
I also think the text and button should be aligned to the top (default, otherwise the space between the text top and the container is not the same as on the side. Bellow is what I think looks best:
<img width="444" alt="Screenshot 2024-06-03 at 09 05 42" src="https://github.com/graasp/graasp-account/assets/39373170/b166d609-dcf9-4c79-83ba-ef0c31b81907">

2024-06-03 07:29 UTC, spaenleh commented on src/components/main/MemberPersonalInformation.tsx
> +      <Grid container spacing={2}>
If using the same spacing, we loose a hierarchical sense when on smaller screens. I think label and setting should be closer together and there should be a larger space between the groups. 
<img width="418" alt="Screenshot 2024-06-03 at 09 07 01" src="https://github.com/graasp/graasp-account/assets/39373170/d4a22b68-b61e-4937-854a-20bcc1f17cc9">

2024-06-03 07:29 UTC, spaenleh commented on src/components/main/MemberPersonalInformation.tsx
> +        </Grid>
This is very repetitive, you should create a component that abstracts this layout.

2024-06-03 07:29 UTC, spaenleh commented on src/components/main/MemberPublicProfile.tsx
> +import TwitterIcon from '@mui/icons-material/Twitter';
We are transitioning to lucide.dev icons. Can you use them instead ?

2024-06-03 07:29 UTC, spaenleh commented on src/components/main/MemberPublicProfile.tsx
> +        <Stack direction="row" spacing={2}>
Same comment about re-usable component here.

2024-06-03 07:29 UTC, spaenleh commented on src/components/main/MemberPublicProfile.tsx
> +              {data?.linkedinID}
I see that currently you display the social network ids as-is. This is what we store, but I am not sure this is what makes the most sens for the user. they are not clickable, they can not verify that it links to the right info. Also it is another way of displaying them. We should have the same way to display them here and in the library member page. We should discuss this in the next meeting.

2024-06-05 14:29 UTC, spaenleh requested changes
Thank you for the changes, I think I will stop bothering you. But I think you should really perform an auto-review to evaluate your code and detect potential refactoring to improve the readability and elegance of the code. This is a good exercise. If you do not find it beautiful, there is maybe a better way to do it. Just something to think about !

2024-06-05 14:29 UTC, spaenleh commented on src/components/main/MemberPersonalInformation.tsx
> +        <MemberProfileItem title={t('PASSWORD_TITLE')} contentId="" />
Specify a value for `contentId`.

2024-06-05 14:29 UTC, spaenleh commented on src/pages/EditPublicProfileScreen.tsx
> +              <Button variant="outlined">{t('CANCEL_BUTTON')}</Button>
I don't think it is logical to have the button say "Cancel" ... "Close" would be more appropriate.

2024-06-05 14:29 UTC, spaenleh commented on src/pages/MemberProfileScreen.tsx
> +      <Divider sx={{ my: 2 }} />
The `my` has no effect on this component (at least from what I can see)
```suggestion
      <Divider />
```

2024-06-05 14:29 UTC, spaenleh commented on src/pages/MemberProfileScreen.tsx
> +      <Typography variant="h4" component="h1">
I like that you used `component` and `variant` but I think we should go for instead:
```suggestion
      <Typography variant="h2" component="h1">
```

2024-06-05 14:29 UTC, spaenleh commented on src/pages/MemberProfileScreen.tsx
> +const MemberProfileScreen = (): JSX.Element | null => {
The return type is too wide, there is no way this returns `null`.

2024-06-05 14:29 UTC, spaenleh commented on src/components/main/MemberPublicProfileItem.tsx
I appreciate the effort on this component, but maybe it tries to do a bit too much things ? Maybe let it only display the links, and display the bio differently. Also change the name to be less linked to the Public Profile. Reflect more what the component is able to do instead of where it is used. This should improve re-usability. Continue like this !

2024-06-05 14:29 UTC, spaenleh commented on src/components/main/MemberPublicProfile.tsx
> +        content={linkedinID ? socialLinks.sanitize('linkedin', linkedinID) : ''}
As much as I like the clever rendering you do in the component, I do not really like that you have to pass the sanitized value twice. Either supply a human readable text for the link content, or use just one prop for the href and display it like that.

2024-06-05 14:29 UTC, spaenleh commented on src/components/main/MemberProfileItem.tsx
> +  </>
Note: I checked and it looks like we would not really need to change the display direction from row to column on small screen sizes.

2024-06-05 14:29 UTC, spaenleh commented on src/components/main/MemberPersonalInformation.tsx
> +        <Link to={EDIT_MEMBER_INFO} className="link">
Not sure why you specified the `link` className ?

2024-06-05 14:29 UTC, spaenleh commented on src/components/main/MemberPublicProfile.tsx
> +const MemberPublicProfile = (): JSX.Element | null => {
Return type can not be `null`.

2024-06-05 14:30 UTC, spaenleh commented
@mariembencheikh I think you should add a container inside the profile page. Recommended max size would be 1000px.

2024-06-06 12:55 UTC, spaenleh approved these changes
Great work ! 🚀

2024-06-07 08:04 UTC, pyphilia requested changes
Thanks for all the changes, I suggest other minor changes, we can merge as soon as you apply them. Thanks 🦆

2024-06-07 08:04 UTC, pyphilia commented on src/pages/MemberProfileScreen.tsx
> +    <Container sx={{ maxWidth: '1000px' }}>
No need, Container has by default a maxWidth of 1200.
```suggestion
    <Container>
```

2024-06-07 08:57 UTC, pyphilia requested changes
I noticed a last bug, please write a test to also verify that the links are correct.

2024-06-07 08:57 UTC, pyphilia commented on src/components/main/MemberPublicProfile.tsx
> +          href={socialLinks.sanitize('linkedin', twitterID)}
```suggestion
          href={socialLinks.sanitize('twitter', twitterID)}
```

2024-06-07 08:57 UTC, pyphilia commented on src/components/main/MemberPublicProfile.tsx
> +          href={socialLinks.sanitize('linkedin', facebookID)}
```suggestion
          href={socialLinks.sanitize('facebook', facebookID)}
```

2024-06-07 12:52 UTC, pyphilia approved these changes

2024-06-07 12:53 UTC, merged