feat: rename Destructive settings to Settings
graasp/graasp-account pull request #259
Opened 2024-06-12 11:50 UTC by mariembencheikh

#258

2024-06-12 13:03 UTC, spaenleh requested changes
I am a bit puzzled by your update to the translation files. Can you explain what you want to do ?

2024-06-12 13:03 UTC, spaenleh commented on src/components/main/DeleteMemberSection.tsx
> +            sx={{ maxWidth: '200px' }}
Do not set maxWidth with pixel units. Instead use `maxWidth: 'min-content'` and in your case set `textWrap: 'no-wrap'` so the button adapts to the size of the content without wrapping on multiple lines.

2024-06-12 13:06 UTC, mariembencheikh commented on src/langs/en.json
> +  "PROFILE_DESTRUCTIVE_SETTINGS_TITLE": "Destructive settings",
This is the title for the delete account, there is other components

2024-06-12 13:07 UTC, mariembencheikh commented on src/langs/ar.json
> +  "MAIN_MENU_SETTINGS": "الإعدادات المدمرة",
ah sorry, ok , maybe i'm not correctly understanding you

2024-06-17 13:10 UTC, pyphilia approved these changes

2024-06-17 13:44 UTC, merged