feat: add uploaded files in storage interface
graasp/graasp-account pull request #314
Opened 2024-07-30 14:27 UTC by mariembencheikh

2024-07-31 05:46 UTC, spaenleh requested changes
Thank you for your work ! 🗄️ 💪 

It would be nice to have a screenshot of the new interface you implemented so we can see how it looks !

2024-07-31 05:46 UTC, spaenleh commented on cypress/e2e/storage.cy.ts
> +              new Date(file.updatedAt).toLocaleString(),
The date is not displayed in human readable format ?

2024-07-31 05:46 UTC, spaenleh commented on cypress/fixtures/members.ts
> +  },
Here you have a data array of length 13 but the page size is 10, so the data array should have length 10. 

I think the fixture should only be a list of the files and in your mock endpoint you build the response by slicing the full list of files into pageSize chunks and return the right chunk with the added totalCount and pagination for the request.

2024-07-31 05:46 UTC, spaenleh commented on cypress/support/commands.ts
> +        mockPagination?: Pagination;
This is not used.

2024-07-31 05:46 UTC, spaenleh commented on cypress/support/commands.ts
> +        files?: Paginated<MemberStorageItem>;
I think the type here should be: 
```suggestion
        files?: MemberStorageItem[];
```
And you build the paginated stuff in the mock response in the server.

2024-07-31 05:46 UTC, spaenleh commented on cypress/support/server.ts
> +      const page = parseInt(params.get('page') ?? '1', 10);
You should not have to specify the radix of the integer conversion. This happens because TS thinks you are using the function from node.js, if you call the function from `window` the issue will disapear:
```suggestion
      const page = window.parseInt(params.get('page') ?? '1');
```

2024-07-31 05:46 UTC, spaenleh commented on cypress/support/server.ts
> +      });
So I see you are already re-creating the pagination information correctly here, so you can remove them from fixture, as they will not be used there.

2024-07-31 05:46 UTC, spaenleh commented on package.json
> +    "@graasp/query-client": "https://github.com/graasp/graasp-query-client#846-add-new-hook-to-get-all-the-uploaded-files-by-current-member-in-storage",
Reminder to use the fixed version once the PR is merged in query-client.

2024-07-31 05:46 UTC, spaenleh commented on src/components/main/MemberStorageFiles.tsx
> +    `${GRAASP_BUILDER_HOST}/${API_ROUTES.buildGetItemRoute(id)}`;
This will not work. This is the Backend route to get the item. For frontend, use the `ClientHostManager` from sdk.

2024-07-31 05:46 UTC, spaenleh commented on src/components/main/MemberStorageFiles.tsx
> +  if (data) {
I usually prefer to order the rendering by:
- has data
- is loading
- is error
As it allows to not have intermediate loading states. In your code this is not the case, but I would prefer to have the error rendering condition after the data condition.

2024-07-31 05:46 UTC, spaenleh commented on src/components/main/MemberStorageFiles.tsx
> +  }
Maybe this can go inside the `if(data)` condition.

2024-07-31 05:46 UTC, spaenleh commented on src/components/main/MemberStorageFiles.tsx
> +                <TableCell id={MEMBER_STORAGE_FILE_NAME_ID}>
An id should be unique here each line has the same id. I think it would be better to build a unique id constituted by the fileId and the cell name: `file_name-${file.id}` for example.

2024-07-31 05:46 UTC, spaenleh commented on src/components/main/MemberStorageFiles.tsx
> +                  {new Date(file.updatedAt).toLocaleString()}
use the `formatDate` to display a human readable date.

2024-07-31 05:46 UTC, spaenleh commented on src/components/main/MemberStorageFiles.tsx
> +          page={pagination.page - 1}
These two got me confused, as they differ from the regular pagination. This is MUI's fault for not making their props consistent.

2024-07-31 05:46 UTC, spaenleh commented on src/components/main/MemberStorageFiles.tsx
> +          count={data?.totalCount}
```suggestion
          count={data.totalCount}
```

2024-07-31 05:46 UTC, spaenleh commented on src/langs/en.json
> +  "MEMBER_STORAGE_FILE_UPDATED_AT": "Updated at",
```suggestion
  "MEMBER_STORAGE_FILE_UPDATED_AT": "Last update",
```

2024-07-31 05:46 UTC, spaenleh commented on src/langs/fr.json
> +  "MEMBER_STORAGE_FILE_UPDATED_AT": "Mis à jour le",
```suggestion
  "MEMBER_STORAGE_FILE_UPDATED_AT": "Dernière mise à jour",
```

2024-07-31 05:46 UTC, spaenleh commented on src/langs/fr.json
> +  "NO_PARENT": "N'a pas de parent",
```suggestion
  "NO_PARENT": "Pas de parent",
```

2024-07-31 05:46 UTC, spaenleh commented on src/langs/fr.json
> +  "STORAGE_FILES_ERROR": "Oops, une erreur est survenue lors de la récupération des fichiers de stockage. Veuillez réessayer plus tard.",
```suggestion
  "STORAGE_FILES_ERROR": "Oops, une erreur est survenue lors de la récupération de la liste des fichiers. Veuillez réessayer plus tard.",
```

2024-08-05 12:36 UTC, pyphilia requested changes
It looks really nice! I still need to test, but I'll you fix those first comments ;) 🌺

2024-08-05 12:36 UTC, pyphilia commented on cypress/support/server.ts
> +        } as Paginated<MemberStorageItem>,
Do you need to cast? Maybe you can cast a bit above, I suppose `result`?

2024-08-05 12:36 UTC, pyphilia commented on src/langs/en.json
> +  "NO_PARENT": "No parent",
```suggestion
  "NO_PARENT": "-",
```

2024-08-05 12:36 UTC, pyphilia commented on src/langs/en.json
> +  "STORAGE_FILES_EMPTY": "No files found."
```suggestion
  "STORAGE_FILES_EMPTY": "You didn't upload any file."
```

2024-08-05 12:36 UTC, pyphilia commented on src/langs/fr.json
> +  "MEMBER_STORAGE_FILE_UPDATED_AT": "Derniére mise à jour",
```suggestion
  "MEMBER_STORAGE_FILE_UPDATED_AT": "Dernière mise à jour",
```

2024-08-05 12:36 UTC, pyphilia commented on src/langs/fr.json
> +  "NO_PARENT": "Pas de parent",
```suggestion
  "NO_PARENT": "-",
```

2024-08-05 12:36 UTC, pyphilia commented on src/langs/fr.json
> +  "STORAGE_FILES_EMPTY": "Aucun fichier trouvé."
```suggestion
  "STORAGE_FILES_EMPTY": "Vous n'avez pas téléchargé de fichier."
```

2024-08-07 08:23 UTC, pyphilia approved these changes

2024-08-07 08:24 UTC, merged