feat: add data export button in settings page
graasp/graasp-account pull request #320
Opened 2024-08-07 10:30 UTC by mariembencheikh

2024-08-07 11:30 UTC, ReidyT approved these changes
Thanks for this PR, it looks good to me, I just let some suggestions 😄. Also, I'm wondering if the button is disabled when the user refresh the page and the email is not sent yet.

2024-08-07 11:30 UTC, ReidyT commented on package.json
> +    "@graasp/query-client": "https://github.com/graasp/graasp-query-client#874-add-member-export-data",
Just a reminder ^^

2024-08-07 11:30 UTC, ReidyT commented on src/config/notifier.ts
> +      message = i18n.t(payload?.message ?? 'EXPORT_ERROR_MESSAGE');
Maybe you can use a const here for `EXPORT_ERROR_MESSAGE` ?

2024-08-07 11:30 UTC, ReidyT commented on src/config/notifier.ts
> +      message = i18n.t(payload?.message ?? 'EXPORT_SUCCESS_MESSAGE');
use a const here too ?

2024-08-07 11:30 UTC, ReidyT commented on src/langs/en.json
> +  "EXPORT_SUCCESS_MESSAGE": "Your request has been sent. An email will be sent to you in several minutes.",
I'd write something like the following (it is only a suggestion :) ).

```suggestion
  "EXPORT_SUCCESS_MESSAGE": "You have successfully requested your data. You will receive an e-mail in a few minutes.",
```

2024-08-07 11:30 UTC, ReidyT commented on src/langs/fr.json
> +  "EXPORT_SUCCESS_MESSAGE": "Votre demande a été envoyée. Vous recevrez un email dans quelques minutes.",
```suggestion
  "EXPORT_SUCCESS_MESSAGE": "Vous avez demandé vos données avec succès. Vous recevrez un e-mail dans quelques minutes.",
```

2024-08-07 11:30 UTC, ReidyT commented on src/langs/en.json
> +  "EXPORT_INFORMATIONS_BUTTON_TEXT": "Start exporting",
I'm wondering if `Start exporting` is the best choice here. I'd write something like the following. I don't know what do you think and what the other thinks ?

```suggestion
  "EXPORT_INFORMATIONS_BUTTON_TEXT": "Request your data",
```

2024-08-07 11:30 UTC, ReidyT commented on src/langs/fr.json
> +  "EXPORT_INFORMATIONS_BUTTON_TEXT": "Commencez à exporter",
```suggestion
  "EXPORT_INFORMATIONS_BUTTON_TEXT": "Demandez vos données",
```

2024-08-08 13:37 UTC, pyphilia commented on package.json
> +    "@graasp/query-client": "https://github.com/graasp/graasp-query-client#874-add-member-export-data",
3.22.0 is ready for you!

2024-08-08 13:45 UTC, pyphilia requested changes
LGTM! I suggested also changes for the texts, please take the best solution between my suggestions and thibault's 🎻

2024-08-08 13:45 UTC, pyphilia commented on cypress/support/server.ts
> +      return reply({ statusCode: StatusCodes.OK });
```suggestion
      return reply({ statusCode: StatusCodes.NO_CONTENT });
```

2024-08-08 13:45 UTC, pyphilia commented on src/langs/fr.json
> +  "EXPORT_INFORMATIONS_TITLE": "Export des données",
```suggestion
  "EXPORT_INFORMATIONS_TITLE": "Télécharger une copie de vos données",
```

2024-08-08 13:45 UTC, pyphilia commented on src/langs/fr.json
> +  "EXPORT_INFORMATIONS_BUTTON_TEXT": "Commencez à exporter",
```suggestion
  "EXPORT_INFORMATIONS_BUTTON_TEXT": "Télécharger vos données",
```

2024-08-08 13:45 UTC, pyphilia commented on src/langs/fr.json
> +  "EXPORT_SUCCESS_MESSAGE": "Votre demande a été envoyée. Vous recevrez un email dans quelques minutes.",
```suggestion
  "EXPORT_SUCCESS_MESSAGE": "Votre demande a été envoyée. Vous recevrez un email avec vos données dans quelques minutes.",
```

2024-08-08 13:45 UTC, pyphilia commented on src/langs/en.json
> +  "EXPORT_INFORMATIONS_BUTTON_TEXT": "Start exporting",
```suggestion
  "EXPORT_INFORMATIONS_BUTTON_TEXT": "Download your data",
```

2024-08-08 13:45 UTC, pyphilia commented on src/langs/en.json
> +  "EXPORT_INFORMATIONS_TITLE": "Export data",
```suggestion
  "EXPORT_INFORMATIONS_TITLE": "Download a copy of your data",
```

2024-08-08 13:45 UTC, pyphilia commented on src/langs/fr.json
> +  "EXPORT_INFORMATIONS_DESCRIPTION": "Vous pouvez télécharger une copie de vos données",
```suggestion
  "EXPORT_INFORMATIONS_DESCRIPTION": "Vous pouvez télécharger une copie de vos données.",
```

2024-08-08 14:34 UTC, pyphilia approved these changes

2024-08-08 14:37 UTC, merged