fix: update dependencies and fix issues
graasp/graasp-account pull request #355
Opened 2024-09-20 09:58 UTC by spaenleh

2024-09-23 13:23 UTC, pyphilia requested changes
Thanks! 🩵

2024-09-23 13:23 UTC, pyphilia commented on src/components/main/MemberPreferences.tsx
> +  if (!member || member?.type === AccountType.Guest) {
I would rather check the member is an `Individual` than not a `Guest`.

2024-09-23 13:23 UTC, pyphilia commented on src/components/main/MemberPreferences.tsx
> +    return false;
Should we return `null`?

2024-09-23 13:23 UTC, pyphilia commented on src/modules/profile/PersonalInformation.tsx
> +  }
Same as above.

2024-09-24 12:30 UTC, spaenleh commented on src/components/main/MemberPreferences.tsx
> +    return false;
I started returning `false` instead of `null` after reading [this article](https://medium.com/@davidkelley87/stop-using-return-null-in-react-a2ebf08fc9cd)

2024-09-30 10:30 UTC, ReidyT commented on src/components/main/MemberPreferences.tsx
> +    return false;
I'm a bit mitigate with this article (check the comments, there is a lot of people that disagree with this practice). Even in the react's documentation they explain how to do conditional rendering using `null` (https://react.dev/learn/conditional-rendering#conditionally-returning-nothing-with-null).

2024-09-30 10:32 UTC, ReidyT requested changes
Thanks for this PR, LGTM! Maybe we should just discuss about returning `null` or `false`? I answered directly in the comment 😄

2024-09-30 12:01 UTC, spaenleh commented on src/components/main/MemberPreferences.tsx
> +    return false;
I looked a bit more and it is true that using `false` can actually have unintended consequences. Thank you for pointing it out. I will revert to using `null` instead. 👍

2024-10-01 13:36 UTC, pyphilia approved these changes

2024-10-01 13:36 UTC, pyphilia commented on src/components/main/MemberPreferences.tsx
> +  }
If this is a page, should we redirect? 
If this is a component, should we enforce that the member exists with the props? Or maybe show an error here?

2024-10-01 13:58 UTC, ReidyT approved these changes
LGTM 🐦‍🔥

2024-10-03 11:42 UTC, spaenleh commented on src/components/main/MemberPreferences.tsx
> +  }
This is a component but should I pass it the member as props ? I do not really like the idea of having to prop drill it. 

Maybe since we have the need for it in a few places, we could have the api return the member only if we request a "real member" ? maybe it should be a different endpoint ? So it would return noting if the user is a guest. And we could remove the checks in the frontend ? @ReidyT @pyphilia @Defferrard

2024-10-03 11:47 UTC, merged