fix: do not allow special characters in username
graasp/graasp-account pull request #356
Opened 2024-09-20 10:05 UTC by MatveyK

Relates to https://github.com/graasp/graasp/pull/1406

2024-09-20 10:12 UTC, spaenleh requested changes
Thank you for this fix, can you add a test that verifies that when inputing a forbidden character the user sees the error message ?

2024-09-20 10:12 UTC, spaenleh commented on src/langs/it.json
> +}
Can you check that your editor is setup to add an empty new line at the end of files ?
```
  "files.trimTrailingWhitespace": true
```

2024-09-20 10:13 UTC, spaenleh commented
@MatveyK Also see about the issue raised by sonarCloud. Maybe there is way to make the regex simpler ? Not sure we need backtracking in there ?

2024-09-24 11:40 UTC, MatveyK commented on src/langs/it.json
> +}
Added.

2024-09-24 11:41 UTC, MatveyK commented
Regex simplified and test added.

2024-09-25 14:30 UTC, pyphilia approved these changes
LGTM, same comment as in https://github.com/graasp/graasp-auth/pull/457#pullrequestreview-2328448199

2024-10-18 13:55 UTC, spaenleh approved these changes

2024-10-18 14:01 UTC, merged