feat: use password status, react hook form
graasp/graasp-account pull request #364
Opened 2024-10-08 14:44 UTC by pyphilia

Show correct informations based on whether the user has a password set. 
Use POST instead of PATCH when the user does not have a password.
Simplify password edition with `react-hook-form`.

https://github.com/user-attachments/assets/601d1606-a748-4dab-b69a-07cf0209718d

https://github.com/user-attachments/assets/e71864f8-35bf-49de-b2e9-755cb143252b

close #359

2024-10-09 08:37 UTC, spaenleh requested changes
Thank you for this feature ! Code look good with the usage of the `react-hook-form` library ! 

I have left a few comments about readability and consistency, let me know what you think !

2024-10-09 08:37 UTC, spaenleh commented on cypress/support/server.ts
> +      return reply('create password');
This should match the reply from the backend: 204.

2024-10-09 08:37 UTC, spaenleh commented on package.json
> +    "@graasp/query-client": "github:graasp/graasp-query-client#password-status-hook",
Reminder

2024-10-09 08:37 UTC, spaenleh commented on src/config/notifier.ts
> +    toast.error(i18n.t(message, { ns: namespaces.messages }));
Is this change correct ? this now translates the message using the translations namespace.

2024-10-09 08:37 UTC, spaenleh commented on src/langs/en.json
> +  "NEW_PASSWORD_SETTINGS_INFORMATION": "Add a password by clicking on the 'Configure' button",
This string does not flow the scope convention: 
```suggestion
  "PASSWORD_SETTINGS_INFORMATION_NEW_PASSWORD": "Add a password by clicking on the 'Configure' button",
```

2024-10-09 08:37 UTC, spaenleh commented on src/modules/profile/password/EditPassword.tsx
> +    : null;
I think it is interesting, but do we need to be so specific about the issue ? See what I did in auth, When an error occurred I tried to point the user to a valid action to perform and usually deduce that a failure could be due to a single cause.

2024-10-09 08:37 UTC, spaenleh commented on src/modules/profile/password/EditPassword.tsx
> +                  type="password"
Allow to see the value of the field in clear text ?

2024-10-09 08:37 UTC, spaenleh commented on src/modules/profile/password/EditPassword.tsx
> +                  autoComplete="current-password"
What is this ?

2024-10-09 08:37 UTC, spaenleh commented on src/modules/profile/password/EditPassword.tsx
> +                  // eslint-disable-next-line react/jsx-props-no-spreading
Should we disable this rule as we benefit from it ?

2024-10-09 08:37 UTC, spaenleh commented on src/modules/profile/password/EditPassword.tsx
> +        {passwordStatus ? (
Should this component be split to ease the flow. Like have a wrapper that fetches the password status and the the rendering of the content in another component ? I find it cleared to split when the components rendered conditionally are big. For a "one line" it is ok to have them inline, but with bigger trees I find having explicit control flow (with `if`) better for readability.

2024-10-11 12:39 UTC, ReidyT reviewed
Thanks for this PR! I haven't check the code for now, I just have questions/comments about the feature's behaviour.

1. When setting a new password, is it possible to display the error live (while entering the new password) instead of when saving?
2. Same comment for when confirming the password (displaying in live that the two passwords are different).
3. Should we check the current password for weaknesses?

2024-10-11 13:19 UTC, pyphilia commented on src/langs/constants.ts
I did it mainly because I used it in tests. I prefer having constants in this case.

2024-10-11 13:28 UTC, pyphilia commented on src/modules/profile/password/EditPassword.tsx
> +                  autoComplete="current-password"
It's for auto complete from the user agent, but we can deal with that later, I'll revert.

2024-10-11 13:30 UTC, pyphilia commented on src/modules/profile/password/EditPassword.tsx
> +                  type="password"
I don't think it's a good practice, I would rather have the eye icon.

2024-10-11 13:31 UTC, spaenleh commented on src/modules/profile/password/EditPassword.tsx
> +                  autoComplete="current-password"
Okay that is fine, I was just curious

2024-10-11 13:32 UTC, ReidyT reviewed
Also I agree with what Basile said, otherwise it looks good to me.

2024-10-11 13:34 UTC, spaenleh commented on src/modules/profile/password/EditPassword.tsx
> +                  type="password"
Okay, the eye is fine for me 👍

2024-10-11 13:41 UTC, pyphilia commented
Thanks for the reviews!

The fields are checked live if you submitted once. I think it's a nice pattern, otherwise you start by checking that an empty password is not strong.. current password is checked as strong password as well.

2024-10-11 13:47 UTC, pyphilia commented on src/modules/profile/password/EditPassword.tsx
> +    : null;
This is mainly to deal with backend errors. Especially "current password is not correct" error. Otherwise it might show "unexpected error instead". So I prefer to be exhaustive. 
I'll refactor the component, so it won't have both create and update at the same time, might be easier to read.

2024-10-11 13:49 UTC, pyphilia commented on src/config/notifier.ts
> +    toast.error(i18n.t(message, { ns: namespaces.messages }));
Might be wrong, but the notifier is only used by query client, which only uses messages. So it was wrong from the very beginning I think?

2024-10-16 08:49 UTC, spaenleh approved these changes
Looks good, I would just like to move the foms down a bit. You may have to include the buttons in the stacks, but I think it will be good anyways.

2024-10-16 08:49 UTC, spaenleh commented on src/modules/profile/password/CreatePassword.tsx
> +    <Box component="form" onSubmit={handleSubmit(onSubmit)}>
I think this form should be inside the `BorderedSection` component

2024-10-16 08:49 UTC, spaenleh commented on src/modules/profile/password/CreatePassword.tsx
> +    <Box component="form" onSubmit={handleSubmit(onSubmit)}>
Actually the "form" should be set on the Stack that is below the title. remove the box component.

2024-10-16 08:49 UTC, spaenleh commented on src/modules/profile/password/DisplayPassword.tsx
> +  const { data: passwordStatus, isLoading: isPasswordStatusLoading } =
Depending on if you want only the initial load or if you want all the loadings you should use `isPending`. `isLoading` has changed semantics in v5.

2024-10-16 08:49 UTC, spaenleh commented on src/modules/profile/password/EditPassword.tsx
> +  const networkError = updateNetworkError;
Why do you rename this ? Do you need it ?

2024-10-16 08:49 UTC, spaenleh commented on src/modules/profile/password/EditPassword.tsx
> +    <Box component="form" onSubmit={handleSubmit(onSubmit)}>
Same comment here, set the form on the Stack on line 111.

2024-10-16 09:15 UTC, ReidyT approved these changes
LGTM

2024-10-16 09:55 UTC, merged