feat: create delete account page
graasp/graasp-account pull request #74
Opened 2024-01-17 09:55 UTC by LinaYahya

2024-01-17 13:29 UTC, spaenleh requested changes
Thank you for this PR ! 
🔥 

Design wise, I would like that new page to be more generic. Think of it as the "Danger zone" where definitive actions can be done to the account and such. So I think:
- update list item on the sidebar should read "Destructive settings" or "Danger Zone"
- the page should present a more welcoming display (not just a simple button)
- Add a red frame around the dangerous actions to warn people they are entering a special place
- use the same style for the title as on the other pages (this should be uniform)
- rename screens and paths to follow the general naming you choose in 1.

2024-01-17 13:29 UTC, spaenleh commented on src/components/main/DeleteMemberDialog.tsx
> +            color: (theme) => theme.palette.grey[500],
Default color here is fine. I don't think there is a big difference. If it is too light people might think that it is disabled

2024-01-17 13:29 UTC, spaenleh commented on src/components/main/DeleteMemberDialog.tsx
> +        fullWidth
Add `disableRestoreFocus` here and `autoFocus` on the TextField

2024-01-17 13:29 UTC, spaenleh commented on src/components/main/DeleteMemberDialog.tsx
>              autoFocus
Remove this.

2024-01-17 13:29 UTC, spaenleh commented on src/components/main/DeleteMemberDialog.tsx
> +            onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
The extra typing here does not look like it is necessary.

2024-01-17 13:29 UTC, spaenleh commented on src/components/main/DeleteMemberDialog.tsx
>            <Grid item xs={12}>
Not sure about the utility of the grids here...

2024-01-17 13:29 UTC, spaenleh commented on src/config/paths.ts
> +export const DELETE_ACCOUNT_PATH = '/delete-account';
I think this route should be changes, if possible to something without a hyphen. 
As we might want to make the page more general, maybe `/manage` ?

2024-01-22 09:02 UTC, LinaYahya commented on src/components/main/DeleteMemberDialog.tsx
> +        <DialogTitle id={alertDialogTitle} sx={{ paddingBottom: 1 }}>
Both are done to reduce padding between title and dialog content

2024-01-24 08:15 UTC, spaenleh requested changes
Thank you for these improvements. 💪 I tried different things locally. I have pushed my changes so you can play with them and see them in context as well as see the exact diff on the `86-delete-account-proposal` branch.

Overall I think we are almost there, I mostly have issues and comments on the style of code. I think it can be more concise and have less specific style overrides (I am sorry but I am not a fan of margin overrides).

So please have a look and let me know if you have comments, questions or if you think my opinions should be challenged (they should).

2024-01-24 08:15 UTC, spaenleh commented on src/components/main/DeleteMemberDialog.tsx
>    const alertDialogDescription = 'alert-dialog-description';
This should be translated and maybe a bit more descriptive

2024-01-24 08:15 UTC, spaenleh commented on src/components/main/DeleteAccount.tsx
> +            <Typography variant="body2" mt={1}>
Remove `mt` here.

2024-01-30 07:12 UTC, spaenleh approved these changes
Nice ! There is just the tiny issue of the break line inside the translation which should be fixed before merging. 💪

2024-01-30 12:10 UTC, spaenleh approved these changes

2024-01-30 14:54 UTC, merged